/** Grouped EMR / charting system presets for employer cards (client-provided list). */
export const EMR_CHARTING_GROUPS = {
  'Hospital EMRs': [
    'Epic',
    'Cerner / Oracle Health Millennium',
    'MEDITECH (Expanse, Magic)',
    'Allscripts Sunrise',
    'Altera Sunrise',
    'Meditech Client/Server',
    'McKesson Horizon Clinicals',
    'Soarian Clinicals',
    'CPSI',
    'Paragon',
    'Medhost EHR',
    'Evident Thrive',
    'QuadraMed',
    'Siemens Invision',
    'VistA/CPRS (VA)',
    'Medsphere OpenVista',
  ],
  'Long-Term Care / Skilled Nursing': [
    'PointClickCare',
    'MatrixCare',
    'SigmaCare',
    'American HealthTech (AHT)',
    'PCC EHR',
    'NetSolutions',
    'Eldermark',
    'WellSky LTC',
    'Optimus EMR',
  ],
  'Home Health & Hospice': [
    'Homecare Homebase (HCHB)',
    'WellSky Home Health',
    'MatrixCare Home Health',
    'KanTime',
    'Axxess',
    'AlayaCare',
  ],
  'Behavioral Health': [
    'Netsmart Avatar',
    'myAvatar',
    'Credible',
    'CareLogic',
    'Welligent',
    'Kipu',
  ],
  'PACS (Imaging)': [
    'GE PACS',
    'Fuji Synapse',
    'Philips IntelliSpace',
    'Siemens Syngo',
    'Carestream PACS',
    'Agfa IMPAX',
    'Sectra PACS',
    'Merge PACS',
    'Intelerad',
    'Visage PACS',
    'RadNet',
  ],
  'RIS (Radiology Information Systems)': [
    'Fuji Synapse RIS',
    'Merge RIS',
    'GE RIS',
    'Philips RIS',
    'Siemens RIS',
    'Sectra RIS',
  ],
  'MRI Systems': [
    'Siemens MRI',
    'GE MRI',
    'Philips MRI',
    'Canon/Toshiba MRI',
    'Hitachi MRI',
  ],
  'CT Systems': [
    'Siemens CT',
    'GE CT',
    'Philips CT',
    'Canon/Toshiba CT',
  ],
  'X-Ray / Radiography': [
    'GE Radiography',
    'Siemens Radiography',
    'Philips DigitalDiagnost',
    'Carestream DR',
    'Shimadzu',
    'Canon DR',
  ],
  Mammography: [
    'Hologic',
    'GE Senographe',
    'Siemens Mammomat',
    'Fujifilm Amulet',
  ],
  Ultrasound: [
    'GE LOGIQ',
    'GE Voluson',
    'Philips EPIQ',
    'Philips Affiniti',
    'Siemens Acuson',
    'Samsung',
    'Mindray',
  ],
  'Cath Lab / IR': [
    'GE Mac-Lab',
    'Siemens Artis',
    'Philips Xper',
    'Merge Hemo',
  ],
  'Laboratory Systems': [
    'Epic Beaker',
    'Cerner PathNet',
    'Sunquest',
    'SoftLab',
    'Orchard Harvest',
    'SCC Soft',
    'Clinisys',
  ],
  'Blood Bank': [
    'SafeTrace',
    'HCLL',
    'Cerner Blood Bank',
  ],
  Pharmacy: [
    'Omnicell',
    'Pyxis',
    'Epic Willow',
    'Cerner PharmNet',
  ],
  'Respiratory Therapy': [
    'Hamilton Ventilators',
    'Servo-i',
    'Servo-u',
    'PB980',
    'V60',
    'Dräger Ventilators',
  ],
  Dialysis: [
    'Clarity',
    'Falcon EHR',
  ],
  'Rehab / PT / OT / SLP': [
    'RehabOptima',
    'Net Health',
    'Casamba',
    'WebPT',
    'Clinicient',
  ],
  'Sleep Lab': [
    'Natus',
    'Alice',
    'Compumedics',
  ],
  EEG: [
    'Nicolet',
    'Nihon Kohden',
    'Cadwell',
  ],
  'EKG/Cardiology': [
    'GE MUSE',
    'Philips IntelliSpace ECG',
    'Mortara',
  ],
  'Cardiac Monitoring': [
    'Philips Telemetry',
    'GE Telemetry',
    'Spacelabs',
    'Welch Allyn',
  ],
} as const satisfies Record<string, readonly string[]>

export type EmrChartingGroupLabel = keyof typeof EMR_CHARTING_GROUPS

export const EMR_CHARTING_GROUP_LABELS = Object.keys(EMR_CHARTING_GROUPS) as EmrChartingGroupLabel[]
